devops_challenge_app/core/urls.py
from django.contrib import admin
from django.urls import path

from tasks.views import get_status, home, run_task

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/<task_id>/", get_status, name="get_status"),
    path("tasks/", run_task, name="run_task"),
    path("", home, name="home"),
]

devops_challenge_app/django_celery/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("feedback.urls")),
]

devops_challenge_app/feedback/urls.py
from django.urls import path

from feedback.views import FeedbackFormView, SuccessView

app_name = "feedback"

urlpatterns = [
    path("", FeedbackFormView.as_view(), name="feedback"),
    path("success/", SuccessView.as_view(), name="success"),
]

devops_challenge_app/feedback/models.py
# from django.db import models

# Create your models here.

devops_challenge_app/feedback/forms.py
from django import forms
from feedback.tasks import send_feedback_email_task

class FeedbackForm(forms.Form):
    email = forms.EmailField(label="Email Address")
    message = forms.CharField(
        label="Message", widget=forms.Textarea(attrs={"rows": 5})
    )

    def send_email(self):
        send_feedback_email_task.delay(
            self.cleaned_data["email"], self.cleaned_data["message"]
        )

devops_challenge_app/feedback/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from feedback.forms import FeedbackForm


class FeedbackFormView(FormView):
    template_name = "feedback/feedback.html"
    form_class = FeedbackForm
    success_url = "/success/"

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class SuccessView(TemplateView):
    template_name = "feedback/success.html"

devops_challenge_app/tasks/views.py
from celery.result import AsyncResult
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from tasks.sample_tasks import create_task


def home(request):
    return render(request, "home.html")


@csrf_exempt
def run_task(request):
    if request.POST:
        task_type = request.POST.get("type")
        task = create_task.delay(int(task_type))
        return JsonResponse({"task_id": task.id}, status=202)


@csrf_exempt
def get_status(request, task_id):
    task_result = AsyncResult(task_id)
    result = {
        "task_id": task_id,
        "task_status": task_result.status,
        "task_result": task_result.result
    }
    return JsonResponse(result, status=200)

devops_challenge_app/feedback/templates/feedback/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/bamboo.css">
    <title>Feedback</title>
</head>
<body>

    {% block content %}

    {% endblock content %}

</body>
</html>

devops_challenge_app/feedback/templates/feedback/feedback.html
{% extends 'feedback/base.html' %}

{% block content %}

    <h1>How are we doing?</h1>
    
    <p>Please send us your feedback.</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"/>
    </form>

{% endblock content %}

devops_challenge_app/feedback/templates/feedback/success.html
{% extends 'feedback/base.html' %}

{% block content %}

<h1>Thank You!</h1>

<p>Your feedback has been recorded.</p>
<p>If you have more to say, you can <a href="{% url 'feedback:feedback' %}">submit another feedback</a> response.</p>

{% endblock content %}

devops_challenge_app/tasks/templates/home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django + Celery + Docker</title>
    <link rel="stylesheet" type="text/css" href="/staticfiles/bulma.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  </head>
  <body>
    <section class="section">
      <div class="container">
        <div class="column is-two-thirds">
          <h1 class="title">Django + Celery + Docker</h1>
          <hr><br>
          <div>
            <h2 class="title is-2">Tasks</h2>
            <h3>Choose a task length:</h3>
            <div class="field is-grouped">
              <p class="control">
                <button class="button is-primary" data-type="1">Short</button>
                <button class="button is-primary" data-type="2">Medium</button>
                <button class="button is-primary" data-type="3">Long</button>
              </p>
            </div>
          </div>
          <br><br>
          <div>
            <h2 class="title is-2">Task Status</h2>
            <br>
            <table class="table is-fullwidth">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Status</th>
                  <th>Result</th>
                </tr>
              </thead>
              <tbody id="tasks">
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>

    <footer class="footer">
      <div class="content container">
        <hr>
        <p><small><span class="text-muted">© <a href="https://mherman.org">Michael Herman</a></span></small></p>
      </div>
    </footer>
    <script type="text/javascript" src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
  </body>
</html>